### ISSUE TITLE
`axe-core-capybara`: Using `:chrome` option uses firefox

### ISSUE THREAD

**Issue by h-parekh** [dequelabs/axe-core-gems#280]
I want to use `axe-core-capybara` gem with my existing framework on chrome and it seems to be going to the default firefox driver instead. 

These are the gem versions in my Gemfile.lock:
```shell
capybara (3.36.0)
selenium-webdriver (4.6.1)
webdrivers (5.2.0)
axe-core-api (4.5.0)
axe-core-capybara (4.5.0)
axe-core-rspec (4.5.0)
```

Here's a snippet to recreate and debug:
```ruby
require 'capybara/rspec'
require 'capybara'
require 'selenium-webdriver'
require 'webdrivers/chromedriver'
require 'axe-capybara'
require 'axe-rspec'

RSpec.feature 'Feature spec', type: :feature, js: true do
  let(:axe_driver) { AxeCapybara.configure(:chrome) { |c| c.jslib_path = "next-version/axe.js" } }

  scenario 'scenario' do
    axe_driver.page.visit 'https://www.deque.com/'
    require 'pry'; binding.pry
  end
end
```

Here's what I see in the pry debugger
```shell
[1] pry(#<RSpec::ExampleGroups::FeatureSpec>)> axe_driver.page.browser
=> #<Selenium::WebDriver::Firefox::Driver:0x..fd5891470f839a1f2 browser=:firefox>

[3] pry(#<RSpec::ExampleGroups::FeatureSpec>)> axe_driver
=> #<Axe::Configuration:0x00007f7bfa545290
 @jslib_path="next-version/axe.js",
 @page=
  #<Capybara::Selenium::Driver:0x00007f7bfa544660
   @app=:chrome,
   @browser=#<Selenium::WebDriver::Firefox::Driver:0x..fd5891470f839a1f2 browser=:firefox>,
   @exit_status=nil,
   @frame_handles={},
   @node_class=Capybara::Selenium::Node,
   @options=
    {:browser=>:firefox,
     :clear_local_storage=>nil,
     :clear_session_storage=>nil,
     :http_client=>#<Capybara::Selenium::PersistentClient:0x00007f7bfa4fd580 @http=#<Net::HTTP 127.0.0.1:4444 open=true>, @open_timeout=nil, @proxy=nil, @read_timeout=nil, @server_url=#<URI::HTTP http://127.0.0.1:4444/>>,
     :native_displayed=>false}>,
 @skip_iframes=nil>
```

**Comment by padmavemulapati** [comment]
@AdnoC Can you please take a look into this issue, this issue still there, but similar issue we had fix in `[devtools-gems](https://github.com/dequelabs/axe-devtools-gems/issues/297)`

**Comment by SantoshDeque** [comment]
Verified in latest develop branch and also with canary build(4.6.1.pre.c43ee49), issue is fixed in Cucumber-Capybara but issue still exists in Rspec-Capybara i.e even though chrome browser is set, it is opening firefox in Rspec-capybara

**Comment by SantoshDeque** [comment]
Verified in latest develop branch, issue still exists in Rspec-Capybara i.e even though chrome browser is set, it is opening firefox in Rspec-capybara

**Comment by SantoshDeque** [comment]
Verified in latest develop branch and issue is fixed for Rspec-Capybara also.

**Comment by padmavemulapati** [comment]
@michael-siek , this issue came back. It got fixed sometime back. Issue appearing only for `rspec-cucumber` remaining all are working as expected

**Comment by padmavemulapati** [comment]
@michael-siek , this is working as expected, might be cache issue earlier. Took the release branch code base and executed the rspec-cucumber using chrome as a default config, its working

https://github.com/dequelabs/axe-core-gems/assets/47409579/361fbad0-7d18-4877-ae31-cfe0f0e18681

**Comment by padmavemulapati** [comment]
@michael-siek , verified with the release-branch code base, issue not there. Its working with the configured browser. (May be my cache problem i was reproduce the issue but after clearing cookies and with the release-branch code base everything looking good) 


Uploading Screen Recording 2024-02-12 at 9.11.45 AM.mov…

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-gems/rspec-cucumber_ |
|**Version** | _release-2024-02-07_codebase_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8 && Windows 11 _ |
|**BrowserDetails**|_Chrome Version 121.0.6167.139 && Firefox 122.0.1_|
